Update boo_on_rdna3.yml

diff --git a/.github/workflows/boo_on_rdna3.yml b/.github/workflows/boo_on_rdna3.yml
--- a/.github/workflows/boo_on_rdna3.yml
+++ b/.github/workflows/boo_on_rdna3.yml
@@ -15,7 +15,6 @@
 name: CI - Boo on RDNA3
 
 on:
-  pull_request:
   workflow_dispatch:
     inputs:
       runner:
@@ -152,7 +151,7 @@ jobs:
        echo "============ Running Prod Conv shape with MIOpen and IREE without tuning ==================="
        iree-boo-driver \
             --commands-file amd-shark-ai-reports/boo/prod_conv_config.txt --csv output_artifacts/rdna3_prod_conv_miopen_iree.csv \
-            --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 \
+            --backend=iree_boo_experimental \
             2>&1 | tee output_artifacts/rdna3_prod_conv_miopen_iree.log || true
 
     - name: Run All Proxy
@@ -162,7 +161,7 @@ jobs:
        ## temporarily disable --backend=torch
        iree-boo-driver \
             --commands-file amd-shark-ai-reports/boo/all_proxy_config.txt --csv output_artifacts/rdna3_all_proxy_miopen_iree.csv \
-            --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 \
+            --backend=iree_boo_experimental \
             2>&1 | tee output_artifacts/rdna3_all_proxy_miopen_iree.log || true
 
     - name: Run Gemm with verify numerics
@@ -171,7 +170,7 @@ jobs:
        echo "============ Running Gemm shape with MIOpen and IREE without tuning ======================================="
        iree-boo-driver \
             --commands-file amd-shark-ai-reports/boo/gemm_config.txt --csv output_artifacts/rdna3_gemm_miopen_iree.csv \
-            --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 \
+            --backend=iree_boo_experimental \
             2>&1 | tee output_artifacts/rdna3_gemm_miopen_iree.log || true
 
     - name: Run Batch Norm with verify numerics
@@ -180,7 +179,7 @@ jobs:
        echo "============ Running Batch norm shape with MIOpen and IREE without tuning ======================================="
        iree-boo-driver \
             --commands-file amd-shark-ai-reports/boo/batch_norm_config.txt --csv output_artifacts/rdna3_batch_norm_miopen_iree.csv \
-            --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 \
+            --backend=iree_boo_experimental \
             2>&1 | tee output_artifacts/rdna3_batch_norm_miopen_iree.log || true
 
     - name: Run Prod Conv NCHW with verify numerics
@@ -208,7 +207,7 @@ jobs:
        pip install -r amdsharktuner/requirements-dev.txt
        iree-boo-driver \
             --commands-file amd-shark-ai-reports/boo/attention_shapes.txt --csv output_artifacts/rdna3_attention_shapes_miopen_iree.csv \
-            --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 \
+            --backend=iree_boo_experimental \
             2>&1 | tee output_artifacts/rdna3_attention_shapes.log || true
 
     - name: Upload log files
@@ -242,39 +241,39 @@ jobs:
         token: ${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}
         path: amd-shark-ai-reports
 
-    # - name: Generate Comparison
-    #   if: github.event_name == 'workflow_dispatch'
-    #   run: |
-    #       cd amd-shark-ai-reports
-    #       export LATEST_DATE=$(ls -1 boo/boo-nightly-gfx110x | sort | tail -n 1)
+    - name: Generate Comparison
+      if: github.event_name == 'workflow_dispatch'
+      run: |
+          cd amd-shark-ai-reports
+          export LATEST_DATE=$(ls -1 boo/boo-nightly-gfx110x | sort | tail -n 1)
 
-    #       if [ "${{ inputs.run_all_proxy }}" = "true" ]; then
-    #         echo "1"
-    #         python github-actions/new_boo_comp.py --current-file "../logs/rdna3_all_proxy_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_all_proxy_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_all_proxy_iree.md" --threshold 0.05 --total-arguments 1071 || echo "failure in all_proxy"
-    #       fi
+          if [ "${{ inputs.run_all_proxy }}" = "true" ]; then
+            echo "1"
+            python github-actions/new_boo_comp.py --current-file "../logs/rdna3_all_proxy_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_all_proxy_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_all_proxy_iree.md" --threshold 0.05 --total-arguments 1071 || echo "failure in all_proxy"
+          fi
 
-    #       if [ "${{ inputs.run_gemm }}" = "true" ]; then
-    #         echo "2"
-    #         python github-actions/new_boo_comp.py --current-file "../logs/rdna3_gemm_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_gemm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_gemm_iree.md" --threshold 0.05 --total-arguments 316 || echo "failure in gemm"
-    #       fi
+          if [ "${{ inputs.run_gemm }}" = "true" ]; then
+            echo "2"
+            python github-actions/new_boo_comp.py --current-file "../logs/rdna3_gemm_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_gemm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_gemm_iree.md" --threshold 0.05 --total-arguments 316 || echo "failure in gemm"
+          fi
 
-    #       if [ "${{ inputs.run_prod_conv }}" = "true" ]; then
-    #         echo "3"
-    #         python github-actions/new_boo_comp.py --current-file "../logs/rdna3_prod_conv_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_prod_conv_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_prod_conv_iree.md" --threshold 0.05 --total-arguments 589 || echo "failure in prod conv"
-    #       fi
+          if [ "${{ inputs.run_prod_conv }}" = "true" ]; then
+            echo "3"
+            python github-actions/new_boo_comp.py --current-file "../logs/rdna3_prod_conv_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_prod_conv_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_prod_conv_iree.md" --threshold 0.05 --total-arguments 589 || echo "failure in prod conv"
+          fi
 
-    #       if [ "${{ inputs.run_batch_norm }}" = "true" ]; then
-    #         echo "4"
-    #         python github-actions/new_boo_comp.py --current-file "../logs/rdna3_batch_norm_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_batch_norm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_batch_norm_miopen_iree.md" --threshold 0.05 --total-arguments 33 || echo "Failure in batchnorm"
-    #       fi
+          if [ "${{ inputs.run_batch_norm }}" = "true" ]; then
+            echo "4"
+            python github-actions/new_boo_comp.py --current-file "../logs/rdna3_batch_norm_miopen_iree.csv" --baseline-file "boo/boo-nightly-gfx110x/${LATEST_DATE}/rdna3_batch_norm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_batch_norm_miopen_iree.md" --threshold 0.05 --total-arguments 33 || echo "Failure in batchnorm"
+          fi
 
-    #       if [ "${{ inputs.run_hipblaslt }}" = "true" ] && [ "${{ inputs.run_gemm }}" = "true" ]; then
-    #         echo "5"
-    #         python github-actions/new_boo_comp_hipblaslt_iree.py --hipblaslt-file "../logs/rdna3_gemm_hipBlaslt-bench.csv" --iree-file "../logs/rdna3_gemm_miopen_iree.csv" --output-csv "../logs/comparison/gemm_iree_hipblaslt_comparison.csv" || echo "failure in hipblaslt"
-    #       fi
+          if [ "${{ inputs.run_hipblaslt }}" = "true" ] && [ "${{ inputs.run_gemm }}" = "true" ]; then
+            echo "5"
+            python github-actions/new_boo_comp_hipblaslt_iree.py --hipblaslt-file "../logs/rdna3_gemm_hipBlaslt-bench.csv" --iree-file "../logs/rdna3_gemm_miopen_iree.csv" --output-csv "../logs/comparison/gemm_iree_hipblaslt_comparison.csv" || echo "failure in hipblaslt"
+          fi
 
-    #       cd ..
-    #       ls -R logs
+          cd ..
+          ls -R logs
 
     - name: Setup reports
       if: always()
