Update ci_boo_on_mi355.yml

diff --git a/.github/workflows/ci_boo_on_mi355.yml b/.github/workflows/ci_boo_on_mi355.yml
--- a/.github/workflows/ci_boo_on_mi355.yml
+++ b/.github/workflows/ci_boo_on_mi355.yml
@@ -244,83 +244,83 @@ jobs:
     if: always()
     runs-on: ubuntu-24.04
     steps:
-    - name: Download log artifacts
-      uses: actions/download-artifact@v7
-      with:
-        name: boo-logs
-        path: logs
-
-    - name: Checkout Target Repo
-      if: always()
-      uses: actions/checkout@v6
-      with:
-        repository: nod-ai/amd-shark-ai-reports
-        token: ${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}
-        path: amd-shark-ai-reports
-
-    - name: Generate Comparison
-      if: github.event_name == 'workflow_dispatch'
-      run: |
-          cd amd-shark-ai-reports
-          export LATEST_DATE=$(ls -1 boo/boo-nightly | sort | tail -n 1)
-
-          if [ "${{ inputs.run_all_proxy }}" = "true" ]; then
-            echo "1"
-            python github-actions/new_boo_comp.py --current-file "../logs/all_proxy_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/all_proxy_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_all_proxy_iree.md" --threshold 0.05 --total-arguments 1071 || echo "failure in all_proxy"
+      - name: Download log artifacts
+        uses: actions/download-artifact@v7
+        with:
+          name: boo-logs
+          path: logs
+  
+      - name: Checkout Target Repo
+        if: always()
+        uses: actions/checkout@v6
+        with:
+          repository: nod-ai/amd-shark-ai-reports
+          token: ${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}
+          path: amd-shark-ai-reports
+  
+      - name: Generate Comparison
+        if: github.event_name == 'workflow_dispatch'
+        run: |
+            cd amd-shark-ai-reports
+            export LATEST_DATE=$(ls -1 boo/boo-nightly | sort | tail -n 1)
+  
+            if [ "${{ inputs.run_all_proxy }}" = "true" ]; then
+              echo "1"
+              python github-actions/new_boo_comp.py --current-file "../logs/all_proxy_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/all_proxy_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_all_proxy_iree.md" --threshold 0.05 --total-arguments 1071 || echo "failure in all_proxy"
+            fi
+  
+            if [ "${{ inputs.run_gemm }}" = "true" ]; then
+              echo "2"
+              python github-actions/new_boo_comp.py --current-file "../logs/gemm_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/gemm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_gemm_iree.md" --threshold 0.05 --total-arguments 320 || echo "failure in gemm"
+            fi
+  
+            if [ "${{ inputs.run_prod_conv }}" = "true" ]; then
+              echo "3"
+              python github-actions/new_boo_comp.py --current-file "../logs/prod_conv_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/prod_conv_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_prod_conv_iree.md" --threshold 0.05 --total-arguments 476 || echo "failure in prod conv"
+            fi
+  
+            if [ "${{ inputs.run_batch_norm }}" = "true" ]; then
+              echo "4"
+              python github-actions/new_boo_comp.py --current-file "../logs/batch_norm_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/batch_norm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_batch_norm_miopen_iree.md" --threshold 0.05 --total-arguments 476 || echo "Failure in batchnorm"
+            fi
+  
+            if [ "${{ inputs.run_hipblaslt }}" = "true" ] && [ "${{ inputs.run_gemm }}" = "true" ]; then
+              echo "5"
+              python github-actions/new_boo_comp_hipblaslt_iree.py --hipblaslt-file "../logs/gemm_hipBlaslt-bench.csv" --iree-file "../logs/gemm_miopen_iree.csv" --output-csv "../logs/comparison/gemm_iree_hipblaslt_comparison.csv" || echo "failure in hipblaslt"
+            fi
+  
+            cd ..
+            ls -R logs
+  
+      - name: Setup reports
+        if: always()
+        run: |
+          git config --global user.name "GitHub Actions Bot"
+          git config --global user.email ""
+          if [ "${{ github.event_name }}" = "schedule" ]; then
+            date=$(date -u +'%Y-%m-%d')
+            OUTPUT_DIR="amd-shark-ai-reports/boo/boo-nightly/$date/"
+            mkdir -p $OUTPUT_DIR
+            echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV
+          else
+            date=$(date -u +'%Y-%m-%d_%H-%M')
+            OUTPUT_DIR="amd-shark-ai-reports/boo/boo-custom-runs/$date/"
+            mkdir -p $OUTPUT_DIR
+            echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV
           fi
-
-          if [ "${{ inputs.run_gemm }}" = "true" ]; then
-            echo "2"
-            python github-actions/new_boo_comp.py --current-file "../logs/gemm_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/gemm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_gemm_iree.md" --threshold 0.05 --total-arguments 320 || echo "failure in gemm"
+  
+      - name: Push artifacts
+        if: always()
+        run: |
+          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
+            mkdir -p $OUTPUT_DIR/comparison/
+            cp -v logs/comparison/*.md $OUTPUT_DIR/comparison/
           fi
-
-          if [ "${{ inputs.run_prod_conv }}" = "true" ]; then
-            echo "3"
-            python github-actions/new_boo_comp.py --current-file "../logs/prod_conv_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/prod_conv_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_prod_conv_iree.md" --threshold 0.05 --total-arguments 476" || echo "failure in prod conv"
-          fi
-
-          if [ "${{ inputs.run_batch_norm }}" = "true" ]; then
-            echo "4"
-            python github-actions/new_boo_comp.py --current-file "../logs/batch_norm_miopen_iree.csv" --baseline-file "boo/boo-nightly/${LATEST_DATE}/batch_norm_miopen_iree.csv" --output-file "../logs/comparison/current_vs_${LATEST_DATE}_batch_norm_miopen_iree.md" --threshold 0.05 --total-arguments 476" || echo "Failure in batchnorm"
-          fi
-
-          if [ "${{ inputs.run_hipblaslt }}" = true ] && [ "${{ inputs.run_gemm }}" = "true" ]; then
-            echo "5"
-            python github-actions/new_boo_comp_hipblaslt_iree.py --hipblaslt-file "../logs/gemm_hipBlaslt-bench.csv" --iree-file "../logs/gemm_miopen_iree.csv" --output-csv "../logs/comparison/gemm_iree_hipblaslt_comparison.csv" || echo "failure in hipblaslt"
-          fi
-
-          cd ..
-          ls -R logs
-
-    - name: Setup reports
-      if: always()
-      run: |
-        git config --global user.name "GitHub Actions Bot"
-        git config --global user.email ""
-        if [ "${{ github.event_name }}" = "schedule" ]; then
-          date=$(date -u +'%Y-%m-%d')
-          OUTPUT_DIR="amd-shark-ai-reports/boo/boo-nightly/$date/"
-          mkdir -p $OUTPUT_DIR
-          echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV
-        else
-          date=$(date -u +'%Y-%m-%d_%H-%M')
-          OUTPUT_DIR="amd-shark-ai-reports/boo/boo-custom-runs/$date/"
-          mkdir -p $OUTPUT_DIR
-          echo "OUTPUT_DIR=$OUTPUT_DIR" >> $GITHUB_ENV
-        fi
-
-    - name: Push artifacts
-      if: always()
-      run: |
-        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
-          mkdir -p $OUTPUT_DIR/comparison/
-          cp -v logs/comparison/*.md $OUTPUT_DIR/comparison/
-        fi
-        cp -v logs/*.csv $OUTPUT_DIR || true
-        cp -v logs/version.txt $OUTPUT_DIR
-        cd amd-shark-ai-reports/boo
-        git pull
-        git add .
-        git commit -m "Add conv report on $(date -u +'%Y-%m-%d')"
-        git push origin main
-        rm -rf ../logs
+          cp -v logs/*.csv $OUTPUT_DIR || true
+          cp -v logs/version.txt $OUTPUT_DIR
+          cd amd-shark-ai-reports/boo
+          git pull
+          git add .
+          git commit -m "Add conv report on $(date -u +'%Y-%m-%d')"
+          git push origin main
+          rm -rf ../logs
