Update ci_boo_on_mi355.yml

diff --git a/.github/workflows/ci_boo_on_mi355.yml b/.github/workflows/ci_boo_on_mi355.yml
--- a/.github/workflows/ci_boo_on_mi355.yml
+++ b/.github/workflows/ci_boo_on_mi355.yml
@@ -13,12 +13,11 @@
 # 4. batch norm with untuned boo and native pytorch
 # 5. prod(nchw) with untuned boo and native pytorch
 # 6. proxy(nchw) with untuned boo and native pytorch
-# 7. Attention shapes with untuned boo and inductor
 
 name: CI - Boo on Mi355
 
 on:
-  pull_request: 
+  pull_request:
   workflow_dispatch:
     inputs:
       commit_hash:
@@ -61,11 +60,6 @@ on:
       #   description: "Run All Proxy NCHW"
       #   type: boolean
       #   default: false
-      run_attention:
-        description: "Run Attention"
-        type: boolean
-        default: false
-
   schedule:
     - cron: "45 11 * * *"
 
@@ -86,7 +80,7 @@ jobs:
     name: "Boo on Mi355"
     strategy:
       matrix:
-        version: ["3.10.12"]
+        version: [3.12]
       fail-fast: false
     runs-on: linux-mi355-1gpu-ossci-nod-ai
     defaults:
@@ -113,33 +107,33 @@ jobs:
         lscpu
         echo ""
         echo "============ GPU Information ============"
-        rocminfo || true
-  #   #     rocm-smi || true
-       
-  #   #     echo ""
-  #   #     echo "============ ROCM Version ============"
-  #   #     cat /opt/rocm/.info/version || echo "ROCM version file not found"
+        rocm-smi || true
+        rocminfo | grep Marketing
+        echo ""
+        echo "============ ROCM Version ============"
+        cat /opt/rocm/.info/version || echo "ROCM version file not found"
 
-  #   - name: Create Python venv
-  #     run: |
-  #       python -m venv ${VENV_DIR}
-  #       source ${VENV_DIR}/bin/activate
-  #       sudo ln -s python3 /usr/bin/python
-  #       echo "${VENV_DIR}/bin" >> $GITHUB_PATH
+    - name: Create Python venv
+      run: |
+        python -m venv ${VENV_DIR}
+        source ${VENV_DIR}/bin/activate
+        sudo ln -s python3 /usr/bin/python
+        echo "${VENV_DIR}/bin" >> $GITHUB_PATH
 
-  #   - name: Setup Environment
-  #     run: |
-  #       mkdir -p output_artifacts
-  #       echo "OUTPUT_ARTIFACTS=$PWD/output_artifacts" >> $GITHUB_ENV
-  #       # python -m pip install \
-  #       #   --index-url https://rocm.nightlies.amd.com/v2/gfx950-dcgpu/ \
-  #       #   -r .github/workflows/ci_boo_torch_pin.txt
-  #       which pip
-  #       which python
-  #       python --version
-  #       # pip install --no-cache-dir "torch>=2.5,<=2.10.0" --index-url https://download.pytorch.org/whl/rocm7.1
-  #       pip install --no-cache-dir typing-extensions>=4.10.0
-  #       pip install --no-cache-dir "torch>=2.5,<=2.10.0" --index-url https://download.pytorch.org/whl/rocm7.1
+    - name: Setup Environment
+      run: |
+        mkdir -p output_artifacts
+        echo "OUTPUT_ARTIFACTS=$PWD/output_artifacts" >> $GITHUB_ENV
+        # python -m pip install \
+        #   --index-url https://rocm.nightlies.amd.com/v2/gfx950-dcgpu/ \
+        #   -r .github/workflows/ci_boo_torch_pin.txt
+        which pip
+        pip install "torch>=2.5,<=2.10.0" --index-url https://download.pytorch.org/whl/rocm7.1
+        pip freeze
+        echo "=================================================="
+        python3 -c "import torch; props = torch.cuda.get_device_properties(0); print(props.name)"
+        echo "=================================================="
+        
 
   #   - name: Install IREE Nightly Packages
   #     if: ${{ !inputs.commit_hash && !inputs.iree_version_tag }}
@@ -200,15 +194,8 @@ jobs:
   #      echo "ROCR_VISIBLE_DEVICES=0" >> $GITHUB_ENV
   #      echo "=================================================="
   #      which pip
-  #      which python3
-  #      python3 --version
   #      python3 -c "import torch; props = torch.cuda.get_device_properties(0); print(props.name)"
   #      echo "=================================================="
-
-  #      echo "============running: modinfo amdgpu | grep ^version=============="
-  #      sudo apt install kmod -y
-  #      modinfo amdgpu | grep ^version
-  #      echo "================================================================="
 
   #   - name: Run Prod Conv with verify numerics
   #     if: always() && (github.event_name == 'schedule' || inputs.run_prod_conv == true)
@@ -263,16 +250,6 @@ jobs:
   #           --commands-file amd-shark-ai-reports/boo/all_proxy_config_nchw.txt --csv output_artifacts/all_proxy_miopen_iree_nchw.csv \
   #           --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
   #           2>&1 | tee output_artifacts/all_proxy_miopen_iree_nchw.log || true
-
-  #   - name: Run Attention
-  #     if: always() && (github.event_name == 'schedule' || inputs.run_attention == true)
-  #     run: |
-  #         echo "============ Running attention shapes with Inductor and IREE without tuning ==================="
-  #         pip install -r amdsharktuner/requirements-dev.txt
-  #         iree-boo-driver \
-  #           --commands-file amd-shark-ai-reports/boo/attention_shapes.txt --csv output_artifacts/attention_shapes_miopen_iree.csv \
-  #           --backend inductor --backend=iree_boo_experimental \
-  #           2>&1 | tee output_artifacts/attention_shapes.log || true
 
   #   - name: Run hipblaslt-bench
   #     if: always() && (github.event_name == 'schedule' || inputs.run_hipblaslt == true)
