Update ci_boo_on_mi355.yml

diff --git a/.github/workflows/ci_boo_on_mi355.yml b/.github/workflows/ci_boo_on_mi355.yml
--- a/.github/workflows/ci_boo_on_mi355.yml
+++ b/.github/workflows/ci_boo_on_mi355.yml
@@ -106,150 +106,152 @@ jobs:
       run: |
         ls
         exit 1
-  #       echo "============ CPU Information ============"
-  #       lscpu
-  #       echo ""
-  #       echo "============ GPU Information ============"
-  #       rocm-smi || true
-  #       rocminfo || true
-  #       echo ""
-  #       echo "============ ROCM Version ============"
-  #       cat /opt/rocm/.info/version || echo "ROCM version file not found"
+        echo "============ CPU Information ============"
+        lscpu
+        echo ""
+        echo "============ GPU Information ============"
+        rocm-smi || true
+        rocminfo || true
+        echo ""
+        echo "============ ROCM Version ============"
+        cat /opt/rocm/.info/version || echo "ROCM version file not found"
 
-  #   - name: Create Python venv
-  #     run: |
-  #       python -m venv ${VENV_DIR}
-  #       source ${VENV_DIR}/bin/activate
-  #       sudo ln -s python3 /usr/bin/python
-  #       echo "${VENV_DIR}/bin" >> $GITHUB_PATH
+    - name: Create Python venv
+      run: |
+        python -m venv ${VENV_DIR}
+        source ${VENV_DIR}/bin/activate
+        sudo ln -s python3 /usr/bin/python
+        echo "${VENV_DIR}/bin" >> $GITHUB_PATH
 
-  #   - name: Setup Environment
-  #     run: |
-  #       mkdir -p output_artifacts
-  #       echo "OUTPUT_ARTIFACTS=$PWD/output_artifacts" >> $GITHUB_ENV
-  #       python -m pip install \
-  #         --index-url https://rocm.nightlies.amd.com/v2/gfx950-dcgpu/ \
-  #         -r .github/workflows/ci_boo_torch_pin.txt
+    - name: Setup Environment
+      run: |
+        mkdir -p output_artifacts
+        echo "OUTPUT_ARTIFACTS=$PWD/output_artifacts" >> $GITHUB_ENV
+        python -m pip install \
+          --index-url https://rocm.nightlies.amd.com/v2/gfx950-dcgpu/ \
+          -r .github/workflows/ci_boo_torch_pin.txt
 
-  #   - name: Install IREE Nightly Packages
-  #     if: ${{ !inputs.commit_hash && !inputs.iree_version_tag }}
-  #     run: |
-  #       pip install --no-index --find-links https://iree.dev/pip-release-links.html --pre --no-deps iree-base-compiler iree-base-runtime
+    - name: Install IREE Nightly Packages
+      if: ${{ !inputs.commit_hash && !inputs.iree_version_tag }}
+      run: |
+        pip install --no-index --find-links https://iree.dev/pip-release-links.html --pre --no-deps iree-base-compiler iree-base-runtime
 
-  #   - name: Install IREE from version tag
-  #     if: ${{ inputs.iree_version_tag != '' }}
-  #     run: |
-  #       pip install \
-  #         --find-links https://iree.dev/pip-release-links.html \
-  #         --upgrade --pre \
-  #         iree-base-compiler==$IREE_VERSION_TAG \
-  #         iree-base-runtime==$IREE_VERSION_TAG
+    - name: Install IREE from version tag
+      if: ${{ inputs.iree_version_tag != '' }}
+      run: |
+        pip install \
+          --find-links https://iree.dev/pip-release-links.html \
+          --upgrade --pre \
+          iree-base-compiler==$IREE_VERSION_TAG \
+          iree-base-runtime==$IREE_VERSION_TAG
 
-  #   - name: Install IREE from source
-  #     if: ${{ inputs.commit_hash != '' }}
-  #     run: |
-  #       git clone https://github.com/iree-org/iree.git && cd iree
-  #       git remote add fork_user https://github.com/${IREE_REMOTE_REPO}
-  #       git fetch fork_user
-  #       git checkout ${IREE_COMMIT_HASH}
-  #       git submodule update --init
-  #       export IREE_HAL_DRIVER_HIP=ON
-  #       export IREE_TARGET_BACKEND_ROCM=ON
-  #       export IREE_ROCM_TEST_TARGET_CHIP=""
-  #       pip install -v runtime/ compiler/
-  #       echo "IREE_SOURCE_HASH=$(git -C . rev-parse --short HEAD)" >> $GITHUB_ENV
+    - name: Install IREE from source
+      if: ${{ inputs.commit_hash != '' }}
+      run: |
+        git clone https://github.com/iree-org/iree.git && cd iree
+        git remote add fork_user https://github.com/${IREE_REMOTE_REPO}
+        git fetch fork_user
+        git checkout ${IREE_COMMIT_HASH}
+        git submodule update --init
+        export IREE_HAL_DRIVER_HIP=ON
+        export IREE_TARGET_BACKEND_ROCM=ON
+        export IREE_ROCM_TEST_TARGET_CHIP=""
+        pip install -v runtime/ compiler/
+        echo "IREE_SOURCE_HASH=$(git -C . rev-parse --short HEAD)" >> $GITHUB_ENV
 
-  #   - name: Install iree-turbine
-  #     run: pip install "git+https://github.com/iree-org/iree-turbine.git"
+    - name: Install iree-turbine
+      run: pip install "git+https://github.com/iree-org/iree-turbine.git"
 
-  #   - name: Print packages
-  #     run: |
-  #       pip freeze > $OUTPUT_ARTIFACTS/version.txt
-  #       if [ -n "$IREE_SOURCE_HASH" ]; then
-  #         sed -i \
-  #           -e "s|iree-base-compiler @ file://[^ ]*|iree-base-compiler $IREE_SOURCE_HASH|g" \
-  #           -e "s|iree-base-runtime @ file://[^ ]*|iree-base-runtime $IREE_SOURCE_HASH|g" \
-  #           $OUTPUT_ARTIFACTS/version.txt
-  #       fi
-  #       cat $OUTPUT_ARTIFACTS/version.txt
+    - name: Print packages
+      run: |
+        pip freeze > $OUTPUT_ARTIFACTS/version.txt
+        if [ -n "$IREE_SOURCE_HASH" ]; then
+          sed -i \
+            -e "s|iree-base-compiler @ file://[^ ]*|iree-base-compiler $IREE_SOURCE_HASH|g" \
+            -e "s|iree-base-runtime @ file://[^ ]*|iree-base-runtime $IREE_SOURCE_HASH|g" \
+            $OUTPUT_ARTIFACTS/version.txt
+        fi
+        cat $OUTPUT_ARTIFACTS/version.txt
 
-  #   - name: Download config files
-  #     run: |
-  #      echo "Getting config files"
-  #      git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}@github.com/nod-ai/amd-shark-ai-reports.git
-  #      cd amd-shark-ai-reports
-  #      git sparse-checkout init --cone
-  #      git sparse-checkout set boo/all_proxy_config.txt boo/prod_conv_config.txt boo/gemm_config.txt boo/hipblaslt-bench.sh boo/all_proxy_config_nchw.txt boo/prod_conv_config_nchw.txt boo/batch_norm_config.txt boo/skip_gemm_config.txt
-  #      git checkout main
-  #      cd -
+    - name: Download config files
+      run: |
+       echo "Getting config files"
+       git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}@github.com/nod-ai/amd-shark-ai-reports.git
+       cd amd-shark-ai-reports
+       git sparse-checkout init --cone
+       git sparse-checkout set boo/all_proxy_config.txt boo/prod_conv_config.txt boo/gemm_config.txt boo/hipblaslt-bench.sh boo/all_proxy_config_nchw.txt boo/prod_conv_config_nchw.txt boo/batch_norm_config.txt boo/skip_gemm_config.txt
+       git checkout main
+       cd -
 
-  #   - name: Setup environment variables
-  #     run: |
-  #      echo "MIOPEN_FIND_ENFORCE=3" >> $GITHUB_ENV
-  #      echo "PYTHONUNBUFFERED=1" >> $GITHUB_ENV
-  #      echo "ROCR_VISIBLE_DEVICES=0" >> $GITHUB_ENV
+    - name: Setup environment variables
+      run: |
+       echo "MIOPEN_FIND_ENFORCE=3" >> $GITHUB_ENV
+       echo "PYTHONUNBUFFERED=1" >> $GITHUB_ENV
+       echo "ROCR_VISIBLE_DEVICES=0" >> $GITHUB_ENV
 
-  #   - name: Run Prod Conv with verify numerics
-  #     if: always() && (github.event_name == 'schedule' || inputs.run_prod_conv == true)
-  #     run: |
-  #      echo "============ Running Prod Conv shape with MIOpen and IREE without tuning ==================="
-  #      iree-boo-driver \
-  #           --commands-file amd-shark-ai-reports/boo/prod_conv_config.txt --csv output_artifacts/prod_conv_miopen_iree.csv \
-  #           --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
-  #           2>&1 | tee output_artifacts/prod_conv_miopen_iree.log || true
+    # - name: Run Prod Conv with verify numerics
+    #   if: always() && (github.event_name == 'schedule' || inputs.run_prod_conv == true)
+    #   run: |
+    #    echo "============ Running Prod Conv shape with MIOpen and IREE without tuning ==================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/prod_conv_config.txt --csv output_artifacts/prod_conv_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
+    #         2>&1 | tee output_artifacts/prod_conv_miopen_iree.log || true
 
-  #   - name: Run All Proxy with verify numerics
-  #     if: always() && (github.event_name == 'schedule' || inputs.run_all_proxy == true)
-  #     run: |
-  #      echo "============ Running All proxy shape with MIOpen and IREE without tuning ==================="
-  #      iree-boo-driver \
-  #           --commands-file amd-shark-ai-reports/boo/all_proxy_config.txt --csv output_artifacts/all_proxy_miopen_iree.csv \
-  #           --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
-  #           2>&1 | tee output_artifacts/all_proxy_miopen_iree.log || true
+    # - name: Run All Proxy with verify numerics
+    #   if: always() && (github.event_name == 'schedule' || inputs.run_all_proxy == true)
+    #   run: |
+    #    echo "============ Running All proxy shape with MIOpen and IREE without tuning ==================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/all_proxy_config.txt --csv output_artifacts/all_proxy_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
+    #         2>&1 | tee output_artifacts/all_proxy_miopen_iree.log || true
 
-  #   - name: Run Gemm with verify numerics
-  #     if: always() && (github.event_name == 'schedule' || inputs.run_gemm == true)
-  #     run: |
-  #      echo "============ Running Gemm shape with MIOpen and IREE without tuning ======================================="
-  #      iree-boo-driver \
-  #           --commands-file amd-shark-ai-reports/boo/gemm_config.txt --csv output_artifacts/gemm_miopen_iree.csv \
-  #           --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
-  #           2>&1 | tee output_artifacts/gemm_miopen_iree.log || true
+    # - name: Run Gemm with verify numerics
+    #   if: always() && (github.event_name == 'schedule' || inputs.run_gemm == true)
+    #   run: |
+    #    echo "============ Running Gemm shape with MIOpen and IREE without tuning ======================================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/gemm_config.txt --csv output_artifacts/gemm_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
+    #         2>&1 | tee output_artifacts/gemm_miopen_iree.log || true
 
-  #   - name: Run Batch Norm with verify numerics
-  #     if: always() && (github.event_name == 'schedule' || inputs.run_batch_norm == true)
-  #     run: |
-  #      echo "============ Running Batch norm shape with MIOpen and IREE without tuning ======================================="
-  #      iree-boo-driver \
-  #           --commands-file amd-shark-ai-reports/boo/batch_norm_config.txt --csv output_artifacts/batch_norm_miopen_iree.csv \
-  #           --backend=torch --backend=iree_boo_experimental --backend=inductor --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
-  #           2>&1 | tee output_artifacts/batch_norm_miopen_iree.log || true
+    # - name: Run Batch Norm with verify numerics
+    #   if: always() && (github.event_name == 'schedule' || inputs.run_batch_norm == true)
+    #   run: |
+    #    echo "============ Running Batch norm shape with MIOpen and IREE without tuning ======================================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/batch_norm_config.txt --csv output_artifacts/batch_norm_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental --backend=inductor --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
+    #         2>&1 | tee output_artifacts/batch_norm_miopen_iree.log || true
 
-  #   - name: Run Prod Conv NCHW with verify numerics
-  #     if: false
-  #     run: |
-  #      echo "============ Running Prod Conv shape with NCHW layout with MIOpen and IREE without tuning ==================="
-  #      iree-boo-driver \
-  #           --commands-file amd-shark-ai-reports/boo/prod_conv_config_nchw.txt --csv output_artifacts/prod_conv_miopen_iree_nchw.csv \
-  #           --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
-  #           2>&1 | tee output_artifacts/prod_conv_miopen_iree_nchw.log || true
+    # - name: Run Prod Conv NCHW with verify numerics
+    #   if: false
+    #   run: |
+    #    echo "============ Running Prod Conv shape with NCHW layout with MIOpen and IREE without tuning ==================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/prod_conv_config_nchw.txt --csv output_artifacts/prod_conv_miopen_iree_nchw.csv \
+    #         --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
+    #         2>&1 | tee output_artifacts/prod_conv_miopen_iree_nchw.log || true
 
-  #   - name: Run All Proxy NCHW with verify numerics
-  #     if: false
-  #     run: |
-  #      echo "============ Running All proxy shape with NCHW layout with MIOpen and IREE without tuning ==================="
-  #      iree-boo-driver \
-  #           --commands-file amd-shark-ai-reports/boo/all_proxy_config_nchw.txt --csv output_artifacts/all_proxy_miopen_iree_nchw.csv \
-  #           --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
-  #           2>&1 | tee output_artifacts/all_proxy_miopen_iree_nchw.log || true
+    # - name: Run All Proxy NCHW with verify numerics
+    #   if: false
+    #   run: |
+    #    echo "============ Running All proxy shape with NCHW layout with MIOpen and IREE without tuning ==================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/all_proxy_config_nchw.txt --csv output_artifacts/all_proxy_miopen_iree_nchw.csv \
+    #         --backend=torch --backend=iree_boo_experimental --verify-numerics --numerics-reference-dtype=float32 --numerics-min-samples 100 --verbose --numerics-verbose \
+    #         2>&1 | tee output_artifacts/all_proxy_miopen_iree_nchw.log || true
 
-  #   - name: Run Attention
-  #     if: always() && (github.event_name == 'schedule' || inputs.run_prod_conv == true)
-  #     run: |
-  #         # ls
-  #         # echo "============ Running Attention shapes with IREE without tuning ==================="
-  #         # git clone --no-checkout --filter=blob:none https://github.com/nod-ai/amd-shark-ai.git && cd amd-shark-ai/ && git sparse-checkout init --cone
-  #         # git sparse-checkout set amdsharktuner && git checkout main
+    - name: Run Attention
+      if: always() && (github.event_name == 'schedule' || inputs.run_prod_conv == true)
+      run: |
+          ls
+          echo "============"
+          ls ../
+          # echo "============ Running Attention shapes with IREE without tuning ==================="
+          # git clone --no-checkout --filter=blob:none https://github.com/nod-ai/amd-shark-ai.git && cd amd-shark-ai/ && git sparse-checkout init --cone
+          # git sparse-checkout set amdsharktuner && git checkout main
           
           
           
