Update ci_boo_on_mi355.yml

diff --git a/.github/workflows/ci_boo_on_mi355.yml b/.github/workflows/ci_boo_on_mi355.yml
--- a/.github/workflows/ci_boo_on_mi355.yml
+++ b/.github/workflows/ci_boo_on_mi355.yml
@@ -28,6 +28,7 @@ on:
         description: "IREE release version tag"
         required: false
         default: ''
+  pull_request:
   schedule:
     - cron: "45 11 * * *"
 
@@ -77,123 +78,123 @@ jobs:
         sudo ln -s python3 /usr/bin/python
         echo "${VENV_DIR}/bin" >> $GITHUB_PATH
 
-    - name: Setup Environment
-      run: |
-        mkdir -p output_artifacts
-        echo "OUTPUT_ARTIFACTS=$PWD/output_artifacts" >> $GITHUB_ENV
-        source ${VENV_DIR}/bin/activate
-        python -m pip install --force-reinstall \
-          --index-url https://rocm.nightlies.amd.com/v2/gfx950-dcgpu/ \
-          --pre torch
+    # - name: Setup Environment
+    #   run: |
+    #     mkdir -p output_artifacts
+    #     echo "OUTPUT_ARTIFACTS=$PWD/output_artifacts" >> $GITHUB_ENV
+    #     source ${VENV_DIR}/bin/activate
+    #     python -m pip install --force-reinstall \
+    #       --index-url https://rocm.nightlies.amd.com/v2/gfx950-dcgpu/ \
+    #       --pre torch
 
-        pip install "git+https://github.com/iree-org/iree-turbine.git"
+    #     pip install "git+https://github.com/iree-org/iree-turbine.git"
 
-    - name: Install IREE Nightly Packages
-      if: ${{ !inputs.commit_hash && !inputs.iree_version_tag }}
-      run: |
-        pip install -f https://iree.dev/pip-release-links.html --upgrade --pre iree-base-compiler iree-base-runtime
-        pip freeze  > $OUTPUT_ARTIFACTS/version.txt
+    # - name: Install IREE Nightly Packages
+    #   if: ${{ !inputs.commit_hash && !inputs.iree_version_tag }}
+    #   run: |
+    #     pip install -f https://iree.dev/pip-release-links.html --upgrade --pre iree-base-compiler iree-base-runtime
+    #     pip freeze  > $OUTPUT_ARTIFACTS/version.txt
 
-    - name: Install IREE from version tag
-      if: ${{ inputs.iree_version_tag != '' }}
-      run: |
-        pip install \
-          --find-links https://iree.dev/pip-release-links.html \
-          --upgrade --pre \
-          iree-base-compiler==$IREE_VERSION_TAG \
-          iree-base-runtime==$IREE_VERSION_TAG
-        pip freeze  > $OUTPUT_ARTIFACTS/version.txt
+    # - name: Install IREE from version tag
+    #   if: ${{ inputs.iree_version_tag != '' }}
+    #   run: |
+    #     pip install \
+    #       --find-links https://iree.dev/pip-release-links.html \
+    #       --upgrade --pre \
+    #       iree-base-compiler==$IREE_VERSION_TAG \
+    #       iree-base-runtime==$IREE_VERSION_TAG
+    #     pip freeze  > $OUTPUT_ARTIFACTS/version.txt
 
-    - name: Install IREE from source
-      if: ${{ inputs.commit_hash != '' }}
-      run: |
-        git clone https://github.com/iree-org/iree.git && cd iree
-        git remote add fork_user https://github.com/${IREE_REMOTE_REPO}
-        git fetch fork_user
-        git checkout ${IREE_COMMIT_HASH}
-        git submodule update --init
-        export IREE_HAL_DRIVER_HIP=ON
-        export IREE_TARGET_BACKEND_ROCM=ON
-        export IREE_HIP_TEST_TARGET_CHIP=""
-        pip install -v runtime/ compiler/
-        pip freeze  > $OUTPUT_ARTIFACTS/version.txt
-        HASH=$(git -C . rev-parse --short HEAD)
-        sed -i \
-          -e "s|iree-base-compiler @ file://[^ ]*|iree-base-compiler $HASH|g" \
-          -e "s|iree-base-runtime @ file://[^ ]*|iree-base-runtime $HASH|g" \
-          $OUTPUT_ARTIFACTS/version.txt || true
+    # - name: Install IREE from source
+    #   if: ${{ inputs.commit_hash != '' }}
+    #   run: |
+    #     git clone https://github.com/iree-org/iree.git && cd iree
+    #     git remote add fork_user https://github.com/${IREE_REMOTE_REPO}
+    #     git fetch fork_user
+    #     git checkout ${IREE_COMMIT_HASH}
+    #     git submodule update --init
+    #     export IREE_HAL_DRIVER_HIP=ON
+    #     export IREE_TARGET_BACKEND_ROCM=ON
+    #     export IREE_HIP_TEST_TARGET_CHIP=""
+    #     pip install -v runtime/ compiler/
+    #     pip freeze  > $OUTPUT_ARTIFACTS/version.txt
+    #     HASH=$(git -C . rev-parse --short HEAD)
+    #     sed -i \
+    #       -e "s|iree-base-compiler @ file://[^ ]*|iree-base-compiler $HASH|g" \
+    #       -e "s|iree-base-runtime @ file://[^ ]*|iree-base-runtime $HASH|g" \
+    #       $OUTPUT_ARTIFACTS/version.txt || true
 
-    - name: Print packages
-      run: cat $OUTPUT_ARTIFACTS/version.txt
+    # - name: Print packages
+    #   run: cat $OUTPUT_ARTIFACTS/version.txt
 
-    - name: Run all proxy config
-      run: |
-       echo "Getting config files"
-       git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}@github.com/nod-ai/amd-shark-ai-reports.git
-       cd amd-shark-ai-reports
-       git sparse-checkout init --cone
-       git sparse-checkout set boo/all_proxy_config.txt boo/prod_conv_config.txt boo/gemm_config.txt boo/hipblaslt-bench.sh boo/all_proxy_config_nchw.txt boo/prod_conv_config_nchw.txt boo/batch_norm_config.txt
-       git checkout main
-       cd -
-       source ${VENV_DIR}/bin/activate
-       export MIOPEN_FIND_ENFORCE=3
-       export ROCR_VISIBLE_DEVICES=0
+    # - name: Run all proxy config
+    #   run: |
+    #    echo "Getting config files"
+    #    git clone --filter=blob:none --no-checkout https://x-access-token:${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}@github.com/nod-ai/amd-shark-ai-reports.git
+    #    cd amd-shark-ai-reports
+    #    git sparse-checkout init --cone
+    #    git sparse-checkout set boo/all_proxy_config.txt boo/prod_conv_config.txt boo/gemm_config.txt boo/hipblaslt-bench.sh boo/all_proxy_config_nchw.txt boo/prod_conv_config_nchw.txt boo/batch_norm_config.txt
+    #    git checkout main
+    #    cd -
+    #    source ${VENV_DIR}/bin/activate
+    #    export MIOPEN_FIND_ENFORCE=3
+    #    export ROCR_VISIBLE_DEVICES=0
 
-       echo "============ 1. Running Prod Conv shape with MIOpen and IREE without tuning ==================="
-       iree-boo-driver \
-            --commands-file amd-shark-ai-reports/boo/prod_conv_config.txt --csv output_artifacts/prod_conv_miopen_iree.csv \
-            --backend=torch --backend=iree_boo_experimental || true
+    #    echo "============ 1. Running Prod Conv shape with MIOpen and IREE without tuning ==================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/prod_conv_config.txt --csv output_artifacts/prod_conv_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental || true
 
-       echo "============ 2. Running All proxy shape with MIOpen and IREE without tuning ==================="
-       iree-boo-driver \
-            --commands-file amd-shark-ai-reports/boo/all_proxy_config.txt --csv output_artifacts/all_proxy_miopen_iree.csv \
-            --backend=torch --backend=iree_boo_experimental || true
+    #    echo "============ 2. Running All proxy shape with MIOpen and IREE without tuning ==================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/all_proxy_config.txt --csv output_artifacts/all_proxy_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental || true
 
-       echo "============ 3. Running Gemm shape with MIOpen and IREE without tuning ======================================="
-       iree-boo-driver \
-            --commands-file amd-shark-ai-reports/boo/gemm_config.txt --csv output_artifacts/gemm_miopen_iree.csv \
-            --backend=torch --backend=iree_boo_experimental || true
+    #    echo "============ 3. Running Gemm shape with MIOpen and IREE without tuning ======================================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/gemm_config.txt --csv output_artifacts/gemm_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental || true
 
-       echo "============ 4. Running Batch norm shape with MIOpen and IREE without tuning ======================================="
-       iree-boo-driver \
-            --commands-file amd-shark-ai-reports/boo/batch_norm_config.txt --csv output_artifacts/batch_norm_miopen_iree.csv \
-            --backend=torch --backend=iree_boo_experimental || true
+    #    echo "============ 4. Running Batch norm shape with MIOpen and IREE without tuning ======================================="
+    #    iree-boo-driver \
+    #         --commands-file amd-shark-ai-reports/boo/batch_norm_config.txt --csv output_artifacts/batch_norm_miopen_iree.csv \
+    #         --backend=torch --backend=iree_boo_experimental || true
 
-       ## Disabling below two run till the time we have failure debugged, which is happening only on runner machine
-       #echo "============ 4. Running Prod Conv shape with NCHW layout with MIOpen and IREE without tuning ==================="
-       #iree-boo-driver \
-       #     --commands-file amd-shark-ai-reports/boo/prod_conv_config_nchw.txt --csv output_artifacts/prod_conv_miopen_iree_nchw.csv \
-       #     --backend=torch --backend=iree_boo_experimental || true
+    #    ## Disabling below two run till the time we have failure debugged, which is happening only on runner machine
+    #    #echo "============ 4. Running Prod Conv shape with NCHW layout with MIOpen and IREE without tuning ==================="
+    #    #iree-boo-driver \
+    #    #     --commands-file amd-shark-ai-reports/boo/prod_conv_config_nchw.txt --csv output_artifacts/prod_conv_miopen_iree_nchw.csv \
+    #    #     --backend=torch --backend=iree_boo_experimental || true
 
-       #echo "============ 5. Running All proxy shape with NCHW layout with MIOpen and IREE without tuning ==================="
-       #iree-boo-driver \
-       #     --commands-file amd-shark-ai-reports/boo/all_proxy_config_nchw.txt --csv output_artifacts/all_proxy_miopen_iree_nchw.csv \
-       #     --backend=torch --backend=iree_boo_experimental || true
+    #    #echo "============ 5. Running All proxy shape with NCHW layout with MIOpen and IREE without tuning ==================="
+    #    #iree-boo-driver \
+    #    #     --commands-file amd-shark-ai-reports/boo/all_proxy_config_nchw.txt --csv output_artifacts/all_proxy_miopen_iree_nchw.csv \
+    #    #     --backend=torch --backend=iree_boo_experimental || true
 
-    - name: Run hipblaslt-bench
-      run: |
-        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
-        sudo apt install unzip -y
-        unzip awscliv2.zip
-        sudo ./aws/install
-        tarFileName=`aws s3 ls s3://therock-nightly-tarball/ --recursive --no-sign-request | grep '\.tar\.gz$' | grep linux-gfx950 | sort -r | head -1 |  awk '{print $NF}'`
-        echo "Installing $tarFileName"
-        wget https://therock-nightly-tarball.s3.us-east-2.amazonaws.com/${tarFileName}
-        mkdir install
-        tar -xf *.tar.gz -C install
-        export PATH=$PWD/install/bin:$PATH
+    # - name: Run hipblaslt-bench
+    #   run: |
+    #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
+    #     sudo apt install unzip -y
+    #     unzip awscliv2.zip
+    #     sudo ./aws/install
+    #     tarFileName=`aws s3 ls s3://therock-nightly-tarball/ --recursive --no-sign-request | grep '\.tar\.gz$' | grep linux-gfx950 | sort -r | head -1 |  awk '{print $NF}'`
+    #     echo "Installing $tarFileName"
+    #     wget https://therock-nightly-tarball.s3.us-east-2.amazonaws.com/${tarFileName}
+    #     mkdir install
+    #     tar -xf *.tar.gz -C install
+    #     export PATH=$PWD/install/bin:$PATH
 
-        echo "============= 5. Running Gemm Shape with hipblaslt =============================="
-        bash amd-shark-ai-reports/boo/hipblaslt-bench.sh >& output_artifacts/gemm_hipBlaslt-bench.csv
+    #     echo "============= 5. Running Gemm Shape with hipblaslt =============================="
+    #     bash amd-shark-ai-reports/boo/hipblaslt-bench.sh >& output_artifacts/gemm_hipBlaslt-bench.csv
 
-    - name: Upload log files
-      if: always()
-      uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
-      with:
-        name: boo-logs
-        path: |
-          output_artifacts/*.csv
-          output_artifacts/version.txt
+    # - name: Upload log files
+    #   if: always()
+    #   uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
+    #   with:
+    #     name: boo-logs
+    #     path: |
+    #       output_artifacts/*.csv
+    #       output_artifacts/version.txt
 
   # New job to push logs to amd-shark-ai-reports repository
   # Add Comparison change
@@ -220,6 +221,10 @@ jobs:
     - name: Setup reports
       if: always()
       run: |
+        wget \
+          --header="${{ secrets.AMD_SHARK_AI_GITHUB_TOKEN }}" \
+          https://raw.githubusercontent.com/nod-ai/amd-shark-ai-reports/blob/main/github-actions/new_boo_comp.py
+        exit 1
         git config --global user.name "GitHub Actions Bot"
         git config --global user.email ""
         if [ "${{ github.event_name }}" = "schedule" ]; then
